name: Uptime Tracker

on:
  workflow_call:

env:
  RPC_NODE: 'https://rpc.provider-sentry-02.hub-testnet.polypore.xyz'
  API_NODE: 'https://rest.provider-sentry-01.hub-testnet.polypore.xyz'

jobs:
  uptime-tracker:
    runs-on: cosmos-runner-set
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Install wget, curl, and jq
        run: |
          sudo apt-get update
          sudo apt-get install -y wget curl jq

      - name: Set up Python
        uses: actions/setup-python@v7
        with:
          python-version: '3.x'

      - name: Create virtual environment
        run: |
          python -m venv .venv
          echo "$PWD/.venv/bin" >> "$GITHUB_PATH"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Get current running gaiad version
        run: |
          RUNNING_VERSION=$(curl -s $RPC_NODE/abci_info | jq -r '.result.response.version')
          echo "Running gaiad version: $RUNNING_VERSION"
          echo "RUNNING_VERSION=$RUNNING_VERSION" >> $GITHUB_ENV

      - name: Download binary from cosmos/gaia repo
        run: |
          sudo wget -nv https://github.com/cosmos/gaia/releases/download/${{ env.RUNNING_VERSION }}/gaiad-${{ env.RUNNING_VERSION }}-linux-amd64 -O /usr/local/bin/gaiad
          sudo chmod +x /usr/local/bin/gaiad
          gaiad version

      - name: Compute last month
        id: date
        run: echo "year_month=$(date -d 'last month' +%Y-%m)" >> "$GITHUB_OUTPUT"

      - name: Run uptime tracker
        working-directory: src
        run: |
          python uptime_tracker.py \
            -r "$RPC_NODE" \
            -a "$API_NODE" \
            -m ${{ steps.date.outputs.year_month }}

      - name: Upload uptime CSV
        uses: actions/upload-artifact@v7
        with:
          name: uptime-${{ steps.date.outputs.year_month }}
          path: src/${{ steps.date.outputs.year_month }}-*-uptime.csv
